# Add package to board
function not_really_anything() {
	# Configure paths et al, directly on image, not rootfs nor bsp
	cat <<- UBOOT_MENU_CONFIGURATION
		# cat /etc/default/u-boot
		## /etc/default/u-boot - configuration file for u-boot-update(8)
		# Generated by Armbian for board ${BOARD}
		U_BOOT_UPDATE="true"

		U_BOOT_ALTERNATIVES="default recovery live"
		U_BOOT_MENU_LABEL="Armbian GNU/Linux"
		U_BOOT_PARAMETERS="usb-storage.quirks=0x0bda:0x9210:u loglevel=7"
		U_BOOT_TIMEOUT="50"
		U_BOOT_FDT_DIR="/usr/lib/linux-image-"

		#U_BOOT_DEFAULT="l0"
		#U_BOOT_ENTRIES="all"
		#U_BOOT_ROOT=""
		#U_BOOT_FDT=""
	UBOOT_MENU_CONFIGURATION

}
# Run it after installing all kernels
