source "${SRC}/config/sources/families/include/meson64_common.inc"

if [[ $BOARD = t95z ]]; then
	display_alert "HACK for t95z" "Not using the real BOOTBRANCH '${BOOTBRANCH}' built u-boot, instead blob from Khadas VIM2" "wrn"
	# temporally workaround - using prebuild u-boot from https://github.com/khadas/khadas-uboot/releases/tag/0.17
	UBOOT_TARGET_MAP=";;$SRC/userpatches/packages/blobs/meson/u-boot-vim2-sd.0.17.bin:u-boot.bin"
fi

family_tweaks() {
	:
}

uboot_custom_postprocess() {
	if [[ $BOARD == t95z ]]; then
		uboot_gxl_postprocess_ng $SRC/cache/sources/amlogic-boot-fip/khadas-vim2
	fi
}
