source "${SRC}/config/sources/families/include/meson64_common.inc"

if [[ $BOARD = t95z ]]; then
	display_alert "HACK for t95z" "Not using the real BOOTBRANCH '${BOOTBRANCH}' built u-boot, instead blob from Khadas VIM2" "info"
	# it seems we've some problem with the FIP blobs for vim2, it resets after 'DDR4 chl: Rank0+1 @ 1008MHz' - this board definitely is not DDR4
	# workaround - using prebuild u-boot from https://github.com/khadas/khadas-uboot/releases/tag/0.17
	# this gets us 'DDR3 chl: Rank0+1 @ 912MHz - PASS' which works.
	UBOOT_TARGET_MAP=";;$SRC/userpatches/packages/blobs/meson/u-boot-vim2-sd.0.17.bin:u-boot.bin"
fi

uboot_custom_postprocess() {
	:
}
