source common-rpardini.conf           # common stuff for all my builds. activates a bunch of extensions.
export BOARD=uefi-x86                 # a new 'board'. you'll soon discover truths.
enable_extension "image-output-qcow2" # Output should be qcow2

user_config__metadata_cloud_config() {
	export SERIALCON="ttyS0"                   # For Oracle VMs on AMD micro stuff
	export UEFI_EXPORT_KERNEL_INITRD="yes"     # Export the initrd and kernel for meta, just like DKB
	export CLOUD_INIT_EXTRA_VERSION="metadata" # For the 'real cloud' version, we skip the c-i config and add a version to the build
	export SKIP_CLOUD_INIT_CONFIG="yes"
}
