# common stuff for all my builds. activates a bunch of extensions.
source common-rpardini.conf
export BOARD=rpi4b
export BRANCH=edge # edge = mainline built-from source; current = Ubuntu's default raspi kernel
