###
### Generic Configuration. BOARD should be defined via ENVIRONMENT, not command line.
###
echo "rpardini-generic-vlc-wifi config for ${BOARD}"

export CLOUD_IMAGE=no                        # This is not a cloud image, otherwise my config will enable it
source common-rpardini.conf                  # common stuff for all my builds. activates a bunch of extensions.
enable_extension "tailscale-client"          # Add tailscale client
enable_extension "hostname-from-mac-address" # Set hostname to board and mac address from ethernet early during boot
enable_extension "add-ssh-keys"              # Add static ssh keys to authorized_keys directly
enable_extension "vlc-headless"              # Add and enable VLC remoting
enable_extension "wifi-hotspot"              # Enable NetworkManager hotspot on wifi

# Defaults for this build
export BRANCH=current # Standard kernel 5.15 in general
export RELEASE=impish # stable Ubuntu
export BOARD=${BOARD} # Whatever board comes

# Hack, use 'classic' BRANCH for tinker
if [[ "${BOARD}" == "tinkerboard-2" ]]; then
	export BRANCH=classic
	display_alert "Use classic for tinkerboard-2" "${BRANCH}" "warn"
fi

# Disable Armbian repo, too crazy
function user_config__common_vlc_disable_repo() {
	export SKIP_ARMBIAN_REPO=yes # Avoid problems with armbian repo out of sync
}

function user_config__common_vlc_full_firmware() {
	export BOARD_FIRMWARE_INSTALL="-full" # Install full firmware
}

if [[ "${VM}" == "yes" ]]; then
	echo "Activating VM mode..."
	# stuff for running in a kvm vm, with pcie passthrough of an USB controller with audio and wifi
	# eg `elquicko armbian --name dev01 --only-locally-built --release impish --boot-type DirectKernel --cpus 2 --mac "52:54:00:01:03:01" --ram 4 && virsh console --domain dev01`
	enable_extension "image-output-qcow2" # Output should be qcow2
	user_config__metadata_cloud_config() {
		export SERIALCON="ttyS0"               # kvm serial
		export UEFI_EXPORT_KERNEL_INITRD="yes" # Export the initrd and kernel for DirectKernel boot
	}
fi

if [[ "${VMWARE}" == "yes" ]]; then
	echo "Activating VMWare mode..."
	enable_extension "image-output-ovf" # Output should be vmdk + vmx etc
fi
