###
### Generic Configuration. BOARD should be defined via ENVIRONMENT, not command line.
###
echo "rpardini-generic-vlc-wifi config for ${BOARD}"

export CLOUD_IMAGE=no       # This is not a cloud image, otherwise my config will enable it
source common-rpardini.conf # common stuff for all my builds. activates a bunch of extensions.

enable_extension "tailscale-client" # Add tailscale client
enable_extension "add-ssh-keys"     # Add static ssh keys to authorized_keys directly
enable_extension "vlc-headless"     # Add and enable VLC remoting, directly to ALSA, with autoconfig and media
enable_extension "wifi-hotspot"     # Enable NetworkManager hotspot on wifi, with early/auto config via USB key
enable_extension "control-service"  # Control Service deployment.

# Defaults for this build
export BRANCH=current                              # Standard kernel 5.15 in general
export RELEASE=jammy                               # stable Ubuntu
export BOARD=${BOARD}                              # Whatever board comes
export PRODUCT_VENDOR="${PRODUCT_VENDOR:-awesome}" # override via env

# Hack, use 'edge' BRANCH for tinker
if [[ "${BOARD}" == "tinkerboard-2" ]]; then
	display_alert "Use BRANCH=edge for tinkerboard-2" "${BRANCH}" "warn"
	export BRANCH=edge

	display_alert "Using TB2's lsmod" "TB2 lsmod" "info"
	enable_extension "kernel-localmodconfig"
	export KERNEL_CONFIG_FROM_LSMOD="tb2-media"
fi

# Hack, use 'ddk' BRANCH for rpi4b.
if [[ "${BOARD}" == "rpi4b" ]]; then
	export BRANCH=ddk
	display_alert "Use BRANCH=ddk for rpi4b" "${BRANCH}" "warn"
fi

# Disable Armbian repo, too crazy
function user_config__common_vlc_disable_repo() {
	export SKIP_ARMBIAN_REPO=yes # Avoid problems with armbian repo out of sync
}

function user_config__common_vlc_full_firmware() {
	export BOARD_FIRMWARE_INSTALL="-full" # Install full firmware
}

if [[ "${VM}" == "yes" ]]; then
	echo "Activating VM mode..."
	# stuff for running in a kvm vm, with pcie passthrough of an USB controller with audio and wifi
	# or `elquicko armbian --name dev01 --only-locally-built --release jammy --boot-type DirectKernel --cpus 2 --ram 4 --mac "52:54:00:01:03:01" && virsh console --domain dev01`
	export BRANCH=ddk
	export SHOW_LOG=yes
	export SHOW_COMMAND=yes
	export SHOW_GROUP=yes
	export SHOW_DEBUG=yes
	enable_extension "image-output-qcow2" # Output should be qcow2
	user_config__metadata_cloud_config() {
		export SERIALCON="ttyS0"               # kvm serial
		export UEFI_EXPORT_KERNEL_INITRD="yes" # Export the initrd and kernel for DirectKernel boot
	}
fi

if [[ "${VMWARE}" == "yes" ]]; then
	echo "Activating VMWare mode..."
	enable_extension "image-output-ovf" # Output should be vmdk + vmx etc
fi
