# common stuff for all my builds. activates a bunch of extensions.
source common-rpardini.conf

###
### Configuration. Points to the board, which has all the HW specific details, like DTBs etc.
###
export BOARD=odroidn2
export BRANCH=current

# early config hook, after family set variables. used for overrides
config_tweaks_post_family_config__use_specific_kernel_version() {
	# My own bootscript (seeds armbianEnv.txt)
	export BOOTENV_FILE='serial_debug.txt'
}
