source common-rpardini.conf                   # common stuff for all my builds. activates a bunch of extensions.
export BOARD=uefi-x86                         # a new 'board'. you'll soon discover truths.
enable_extension "dual-root-lvm"              # Use dual root hack with lvm marker.
enable_extension "rootfs_e2img_inside_rootfs" # Include a "rootfs image" but dual root does many tricks with it. I mean many.

user_config__dual_root_arm64_config() {
	export CLOUD_INIT_EXTRA_VERSION="dualroot"
	export SERIALCON="ttyS0" # For Oracle VMs on AMD micro stuff
	export DUAL_ROOT_FIXED_IMAGE_SIZE_GB=12    # Use a huge fixed image size. 12Gb will result in around 8/4gb root/fake
	export UEFI_GRUB_TERMINAL="serial console" # this will go in grub.d config, so Grub displays on serial and console
	export UEFI_GRUB_TIMEOUT=10                # Bump the grub timeout so we have plenty of time to connect to it
	export CLOUD_INIT_CONFIG_LOCATION="/boot"  # use /boot for cloud-init as well
	export UEFI_ENABLE_BIOS_AMD64="no"         # Disable the BIOS-too aspect of UEFI on amd64 - dualroot is exclusively UEFI
}
