# common stuff for all my builds. activates a bunch of extensions.
source common-rpardini.conf

###
### Generic Configuration. BOARD should be defined via command line
###
echo "rpardini-generic config for ${BOARD}"
declare -g BRANCH=${BRANCH:-current}

# early config hook, after family set variables. used for overrides
config_tweaks_post_family_config__use_specific_kernel_version() {
	display_alert "Enabling rpardini serial debug" "rpardini serial debug bootenv" "info"
	# My own bootscript (seeds armbianEnv.txt)
	declare -g BOOTENV_FILE='serial_debug.txt'
}

