# Amlogic S905D3 quad core 2GB RAM SoC eMMC GBE USB3 SPI
BOARD_NAME="Khadas VIM3L"
BOARDFAMILY="meson-sm1"
BOOTCONFIG="khadas-vim3l_defconfig"
KERNEL_TARGET="current,edge,khadas"
FULL_DESKTOP="yes"
SERIALCON="ttyAML0"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="amlogic/meson-sm1-khadas-vim3l.dtb"
ASOUND_STATE="asound.state.khadas-vim3l"

export KERNEL_MAJOR_MINOR="5.16" # Major and minor versions of this kernel. For mainline caching.
KERNELBRANCH='branch:linux-5.16.y'
KERNELPATCHDIR='archive/meson64-5.16-khadas'
LINUXCONFIG="linux-meson64-edge" # use edge's config, I don't care.

# Work to be done:
# u-boot: not worth it; can switch usb x pcie directly via i2c @TODO: add to docs
# kernel: mcu errors, others, regulators in 5.17.x; try a new kernel?
# firmware: missing wifi firmware, add and fix
# asound for vim3l
# copy and fix instructions from vim3: use krescue, fast zero emmc, burn armbian to SD, sata-nand-install.
