# Amlogic S905Y2 512MB/1GB/2GB/4GB RAM eMMC USB3 WiFi BT
BOARD_NAME="Radxa Zero"
BOARDFAMILY="meson-g12a"
BOOTCONFIG="radxa-zero_config"
CPUMIN=6660000
CPUMAX=1800000
KERNEL_TARGET="legacy,current,edge"
FULL_DESKTOP="yes"
FORCE_BOOTSCRIPT_UPDATE="yes"
BOOT_LOGO="desktop"
ASOUND_STATE="asound.state.radxa-zero"
BOOT_FDT_FILE="amlogic/meson-g12a-radxa-zero.dtb"

# Doing a vendor kernel, right here in the board, *without touching family code*
function post_family_config__legacy_radxa_kernel() {
	case $BRANCH in
		legacy)
			display_alert "Using legacy Radxa Kernel" "5.10 radxa legacy for Zero" "warn"

			LINUXFAMILY="vendor-radxa-zero"  # a separate family for this (separate kernel deb)
			export KERNEL_MAJOR_MINOR="5.10" # Major and minor versions of this kernel. For mainline caching.
			KERNELBRANCH='branch:linux-5.10.y'
			KERNELPATCHDIR='vendor/radxa-zero-5.10'
			LINUXCONFIG="linux-meson64-current" # Use the `current` branch's config for this `legacy` kernel
			;;
	esac
}
