# RISC-V StarFive
BOARD_NAME="VisionFive-V2"
BOARDFAMILY="starfive"
KERNEL_TARGET="current,edge"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="starfive/jh7110-visionfive-v2.dtb"
SRC_EXTLINUX="yes"
SRC_CMDLINE="console=ttyS0,115200n8 console=tty0 earlycon=sbi"
BOOTCONFIG=none
